## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

import os, sys
currentdir = os.path.dirname(os.path.realpath("Vacation_Search"))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,2020-12-28 00:53:39,-46.60,168.33,56.52,61,0,9.42,clear sky
1,1,Saskylakh,RU,2020-12-28 00:53:56,71.92,114.08,-13.40,86,100,20.67,overcast clouds
2,2,Yerbogachen,RU,2020-12-28 00:59:41,61.28,108.01,-21.75,85,100,8.68,overcast clouds
3,3,Busselton,AU,2020-12-28 00:53:25,-33.65,115.33,66.00,54,0,7.00,clear sky
4,4,Mataura,NZ,2020-12-28 00:53:20,-46.19,168.86,72.34,29,0,2.30,clear sky

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                      (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,Guanica,PR,2020-12-28 01:00:31,17.97,-66.91,75.99,84,17,3.29,few clouds
12,12,Rikitea,PF,2020-12-28 00:53:17,-23.12,-134.97,78.58,79,88,14.97,light rain
17,17,Balabac,PH,2020-12-28 01:00:33,7.99,117.06,82.08,79,96,12.46,overcast clouds
19,19,Manokwari,ID,2020-12-28 00:59:52,-0.87,134.08,81.59,75,100,5.32,overcast clouds
23,23,Hithadhoo,MV,2020-12-28 00:53:37,-0.60,73.08,81.82,74,33,7.20,scattered clouds
25,25,Bambous Virieux,MU,2020-12-28 00:58:34,-20.34,57.76,77.00,83,40,11.41,shower rain
32,32,Kununurra,AU,2020-12-28 01:00:36,-15.77,128.73,86.00,74,90,2.59,overcast clouds
36,36,Cabo San Lucas,MX,2020-12-28 00:49:16,22.89,-109.91,75.20,43,5,11.41,clear sky
48,48,Mopipi,BW,2020-12-28 01:00:40,-21.18,24.88,77.72,61,98,11.92,light rain
54,54,Hilo,US,2020-12-28 00:53:29,19.73,-155.09,77.00,69,75,6.93,light rain

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                165
City                   165
Country                165
Date                   165
Lat                    165
Lng                    165
Max Temp               165
Humidity               165
Cloudiness             165
Wind Speed             165
Current Description    165
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,Guanica,PR,2020-12-28 01:00:31,17.97,-66.91,75.99,84,17,3.29,few clouds
12,12,Rikitea,PF,2020-12-28 00:53:17,-23.12,-134.97,78.58,79,88,14.97,light rain
17,17,Balabac,PH,2020-12-28 01:00:33,7.99,117.06,82.08,79,96,12.46,overcast clouds
19,19,Manokwari,ID,2020-12-28 00:59:52,-0.87,134.08,81.59,75,100,5.32,overcast clouds
23,23,Hithadhoo,MV,2020-12-28 00:53:37,-0.60,73.08,81.82,74,33,7.20,scattered clouds
...,...,...,...,...,...,...,...,...,...,...,...
694,694,Porto Nacional,BR,2020-12-28 01:03:17,-10.71,-48.42,77.00,94,20,4.70,light rain
698,698,Santa Rosa,PH,2020-12-28 00:50:45,14.31,121.11,79.00,88,75,3.36,broken clouds
699,699,Fare,PF,2020-12-28 00:55:28,-16.70,-151.02,81.61,67,3,6.82,clear sky
700,700,Robertsport,LR,2020-12-28 01:03:18,6.75,-11.37,80.17,83,61,8.88,broken clouds
704,704,Kloulklubed,PW,2020-12-28 00:55:16,7.04,134.26,78.80,88,90,3.36,overcast clouds

In [8]:
#Double check the na rows were dropped if any 
preferred_cities_df.count()

City_ID                165
City                   165
Country                165
Date                   165
Lat                    165
Lng                    165
Max Temp               165
Humidity               165
Cloudiness             165
Wind Speed             165
Current Description    165
dtype: int64

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Guanica,PR,75.99,few clouds,17.97,-66.91,
12,Rikitea,PF,78.58,light rain,-23.12,-134.97,
17,Balabac,PH,82.08,overcast clouds,7.99,117.06,
19,Manokwari,ID,81.59,overcast clouds,-0.87,134.08,
23,Hithadhoo,MV,81.82,scattered clouds,-0.60,73.08,
25,Bambous Virieux,MU,77.00,shower rain,-20.34,57.76,
32,Kununurra,AU,86.00,overcast clouds,-15.77,128.73,
36,Cabo San Lucas,MX,75.20,clear sky,22.89,-109.91,
48,Mopipi,BW,77.72,light rain,-21.18,24.88,
54,Hilo,US,77.00,light rain,19.73,-155.09,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [15]:
#Doublecheck that hotel names are put into the df 
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Guanica,PR,75.99,few clouds,17.97,-66.91,Copamarina Beach Resort & Spa
12,Rikitea,PF,78.58,light rain,-23.12,-134.97,Pension Maro'i
17,Balabac,PH,82.08,overcast clouds,7.99,117.06,Sing and Swing Lodge
19,Manokwari,ID,81.59,overcast clouds,-0.87,134.08,Swiss Belhotel Manokwari
23,Hithadhoo,MV,81.82,scattered clouds,-0.60,73.08,Scoop Guest House
25,Bambous Virieux,MU,77.00,shower rain,-20.34,57.76,Casa Tia Villa
32,Kununurra,AU,86.00,overcast clouds,-15.77,128.73,Hotel Kununurra
36,Cabo San Lucas,MX,75.20,clear sky,22.89,-109.91,Hotel Tesoro Los Cabos
48,Mopipi,BW,77.72,light rain,-21.18,24.88,
54,Hilo,US,77.00,light rain,19.73,-155.09,Hilo Hawaiian Hotel

In [16]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[hotel_df["Hotel Name"]!=""]

In [17]:
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Guanica,PR,75.99,few clouds,17.97,-66.91,Copamarina Beach Resort & Spa
12,Rikitea,PF,78.58,light rain,-23.12,-134.97,Pension Maro'i
17,Balabac,PH,82.08,overcast clouds,7.99,117.06,Sing and Swing Lodge
19,Manokwari,ID,81.59,overcast clouds,-0.87,134.08,Swiss Belhotel Manokwari
23,Hithadhoo,MV,81.82,scattered clouds,-0.60,73.08,Scoop Guest House
25,Bambous Virieux,MU,77.00,shower rain,-20.34,57.76,Casa Tia Villa
32,Kununurra,AU,86.00,overcast clouds,-15.77,128.73,Hotel Kununurra
36,Cabo San Lucas,MX,75.20,clear sky,22.89,-109.91,Hotel Tesoro Los Cabos
54,Hilo,US,77.00,light rain,19.73,-155.09,Hilo Hawaiian Hotel
66,Anloga,GH,80.60,few clouds,5.79,0.90,Pin Drop Hotel

In [19]:
# 8a. Create the output File (CSV)
WeatherPy_vacation= clean_hotel_df 
WeatherPy_vacation= "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(WeatherPy_vacation, index_label="City_ID")

In [30]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [23]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))